export const ADD_PUBLICATION = 'ADD_PUBLICATION';
export const LIST_PUBLICATIONS = 'LIST_PUBLICATIONS';
export const LIST_COMMENTS = 'LIST_COMMENTS';
export const ERROR_PUBLICATION = 'ERROR_PUBLICATION';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REACTIONS = 'REACTIONS';